spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:10001
        username: admin
        password: admin
        instance:
          service-base-url: http://127.0.0.1:10001
server:
  port: 10002
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  version: 1.1.0
  groupId: 1.2.3
  artifactId: 1.3.2
