spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:10001
server:
  port: 10002
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
