spring:
  application:
    name: admin-server
  mail:
    host: smtp.qq.com
    username: 857454370@qq.com
    password: pmktcuqpjcwxbddd
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: 857454370@qq.com
          from: 842230914@qq.com
server:
  port: 10001
